spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoshuttle
    username: postgres
    password: dbdbdb326
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
