spring:
  datasource:
    url: jdbc:mysql://localhost:5432/hoshuttle
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
